name: tripdiffusion
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.0
  - tqdm>=4.62.0
  - pip:
      - torch>=1.10.0
